/*
 * PortDriver_Lcfg.c
 *
 * Created: 4/8/2020 6:32:27 PM
 *  Author: Khaled
 */ 

#include "PortDriver_Lcfg.h" 
 

PortDriver_CfgType PortDriver_CfgArr[NUM_OF_ACTIVATED_CHANNELS] =
{/* Channel		                 PortDriver_Channel_Direction             PortDriver_Channel_Current_mA                      PortDriver_Channel_SlewRate                PortDriver_Channel_Attachment                    PortDriver_Channel_Function             PortDriver_Channel_Exti  */
	{PORTDRIVER_CHANNEL_E2,      PORTDRIVER_CHANNEL_DIRECTION_INPUT,      PORTDRIVER_CHANNEL_CURRENT_mA_2,                   PORTDRIVER_CHANNEL_SLEWRATE_DISABLE,       PORTDRIVER_CHANNEL_ATTACHMENT_NOTCONNECTED,      PORTDRIVER_CHANNEL_FUNCTION_E2_AIN1 ,      PORTDRIVER_CHANNEL_EXTI_DISABLE }
	,{PORTDRIVER_CHANNEL_B4,      PORTDRIVER_CHANNEL_DIRECTION_OUTPUT,      PORTDRIVER_CHANNEL_CURRENT_mA_2,                   PORTDRIVER_CHANNEL_SLEWRATE_DISABLE,       PORTDRIVER_CHANNEL_ATTACHMENT_NOTCONNECTED,      PORTDRIVER_CHANNEL_FUNCTION_X_DIO ,      PORTDRIVER_CHANNEL_EXTI_DISABLE }
,		{PORTDRIVER_CHANNEL_B5,      PORTDRIVER_CHANNEL_DIRECTION_OUTPUT,      PORTDRIVER_CHANNEL_CURRENT_mA_2,                   PORTDRIVER_CHANNEL_SLEWRATE_DISABLE,       PORTDRIVER_CHANNEL_ATTACHMENT_NOTCONNECTED,      PORTDRIVER_CHANNEL_FUNCTION_X_DIO ,      PORTDRIVER_CHANNEL_EXTI_DISABLE }
,		{PORTDRIVER_CHANNEL_F1,      PORTDRIVER_CHANNEL_DIRECTION_OUTPUT,      PORTDRIVER_CHANNEL_CURRENT_mA_2,                   PORTDRIVER_CHANNEL_SLEWRATE_DISABLE,       PORTDRIVER_CHANNEL_ATTACHMENT_NOTCONNECTED,      PORTDRIVER_CHANNEL_FUNCTION_X_DIO ,      PORTDRIVER_CHANNEL_EXTI_DISABLE }

	};
