#ifndef _NVIC_TYPES_H
#define _NVIC_TYPES_H

#include "../std_types.h"

                          /*NVIC Types.h */
						  
typedef uint8_t SubGroup_PriorityType;
typedef uint8_t Group_PriorityType;
typedef enum
{
	NVIC_GPIO_PORT_A,
	NVIC_GPIO_PORT_B,
	NVIC_GPIO_PORT_C,
	NVIC_GPIO_PORT_D,
	NVIC_GPIO_PORT_E,
	NVIC_UART_0,
	NVIC_UART_1,
	NVIC_SSI_0,
	NVIC_I2C_0,
	NVIC_PWM0_FAULT,
	NVIC_PWM0_GENERATOR_0,
	NVIC_PWM0_GENERATOR_1,
	NVIC_PWM0_GENERATOR_2,
	NVIC_QEI_0,
	NVIC_ADC0_SEQUENCE_0,
	NVIC_ADC0_SEQUENCE_1,
	NVIC_ADC0_SEQUENCE_2,
	NVIC_ADC0_SEQUENCE_3,
	NVIC_WATCHDOG_TIMERS_0_1,
	NVIC_16_32_BIT_TIMER_0A,
	NVIC_16_32_BIT_TIMER_0B,
	NVIC_16_32_BIT_TIMER_1A,
	NVIC_16_32_BIT_TIMER_1B,
	NVIC_16_32_BIT_TIMER_2A,
	NVIC_16_32_BIT_TIMER_2B,
	NVIC_ANALOG_COMPARETOR_0,
	NVIC_ANALOG_COMPARETOR_1,
	NVIC_RESERVED_0,
	NVIC_SYSTEM_CONTROL,
	NVIC_FLASH_MEMORY_CONTROL_AND_EEPROM_CONTROL,
	NVIC_GPIO_PORT_F,
	NVIC_RESERVED_1,
	NVIC_RESERVED_2,
	NVIC_UART_2,
	NVIC_SSI_1,
	NVIC_16_32_BIT_TIMER_3A,
	NVIC_16_32_BIT_TIMER_3B,
	NVIC_I2C_1,
	NVIC_QEI_1,
	NVIC_CAN_0,
	NVIC_CAN_1,
	NVIC_RESERVED_3,
	NVIC_RESERVED_4,
	NVIC_HIBERNATION_MODULE,
	NVIC_USB,
	NVIC_PWM0_GENERATOR_3,
	NVIC_uDMA_SOFEWARE,
	NVIC_uDMA_ERROR,
	NVIC_ADC1_SEQUENCE_0,
	NVIC_ADC1_SEQUENCE_1,
	NVIC_ADC1_SEQUENCE_2,
	NVIC_ADC1_SEQUENCE_3,
	NVIC_RESERVED_5,
	NVIC_RESERVED_6,
	NVIC_RESERVED_7,
	NVIC_RESERVED_8,
	NVIC_RESERVED_9,
	NVIC_SSI_2,
	NVIC_SSI_3,
	NVIC_UART_3,
	NVIC_UART_4,
	NVIC_UART_5,
	NVIC_UART_6,
	NVIC_UART_7,
	NVIC_RESERVED_10,
	NVIC_RESERVED_11,
	NVIC_RESERVED_12,
	NVIC_RESERVED_13,
	NVIC_I2C_2,
	NVIC_I2C_3,
	NVIC_16_32_BIT_TIMER_4A,
	NVIC_16_32_BIT_TIMER_4B,
	NVIC_RESERVED_14,
	NVIC_RESERVED_15,
	NVIC_RESERVED_16,
	NVIC_RESERVED_17,
	NVIC_RESERVED_18,
	NVIC_RESERVED_19,
	NVIC_RESERVED_20,
	NVIC_RESERVED_21,
	NVIC_RESERVED_22,
	NVIC_RESERVED_23,
	NVIC_RESERVED_24,
	NVIC_RESERVED_25,
	NVIC_RESERVED_26,
	NVIC_RESERVED_27,
	NVIC_RESERVED_28,
	NVIC_RESERVED_29,
	NVIC_RESERVED_30,
	NVIC_RESERVED_31,
	NVIC_RESERVED_32,
	NVIC_RESERVED_33,
	NVIC_16_32_BIT_TIMER_5A,
	NVIC_16_32_BIT_TIMER_5B,
	NVIC_32_64_BIT_TIMER_0A,
	NVIC_32_64_BIT_TIMER_0B,
	NVIC_32_64_BIT_TIMER_1A,
	NVIC_32_64_BIT_TIMER_1B,
	NVIC_32_64_BIT_TIMER_2A,
	NVIC_32_64_BIT_TIMER_2B,
	NVIC_32_64_BIT_TIMER_3A,
	NVIC_32_64_BIT_TIMER_3B,
	NVIC_32_64_BIT_TIMER_4A,
	NVIC_32_64_BIT_TIMER_4B,
	NVIC_32_64_BIT_TIMER_5A,
	NVIC_32_64_BIT_TIMER_5B,
	NVIC_SYSTEM_EXCEPTION,
	NVIC_RESERVED_34,
	NVIC_RESERVED_35,
	NVIC_RESERVED_36,
	NVIC_RESERVED_37,
	NVIC_RESERVED_38,
	NVIC_RESERVED_39,
	NVIC_RESERVED_40,
	NVIC_RESERVED_41,
	NVIC_RESERVED_42,
	NVIC_RESERVED_43,
	NVIC_RESERVED_44,
	NVIC_RESERVED_45,
	NVIC_RESERVED_46,
	NVIC_RESERVED_47,
	NVIC_RESERVED_48,
	NVIC_RESERVED_49,
	NVIC_RESERVED_50,
	NVIC_RESERVED_51,
	NVIC_RESERVED_52,
	NVIC_RESERVED_53,
	NVIC_RESERVED_54,
	NVIC_RESERVED_55,
	NVIC_RESERVED_56,
	NVIC_RESERVED_57,
	NVIC_RESERVED_58,
	NVIC_RESERVED_59,
	NVIC_PWM1_GENERATOR_0,
	NVIC_PWM1_GENERATOR_1,
	NVIC_PWM1_GENERATOR_2,
	NVIC_PWM1_GENERATOR_3,
	NVIC_PWM1_FAULT	
}IntNumType;

typedef struct
{
	IntNumType IntNum;
	Group_PriorityType Group_Priority;
	SubGroup_PriorityType	SubGroup_Priority;
}NVIC_CfgType;

// Interrupt prioprity Grouping  and subprioprity Grouping moodes //



#define INT_GR_MOODE_0      0 // avaliable ranges -> PriopriyGroup  0:7  , subpriority  0

#define INT_GR_MOODE_1      1 // avaliable ranges -> PriopriyGroup  0:3  , subpriority 0:1

#define INT_GR_MOODE_2		2 // avaliable ranges -> PriopriyGroup 0:1   , subpriority 0:3

#define INT_GR_MOODE_3		3 // avaliable ranges -> PriopriyGroup  0    , subpriority 0:7

#endif 
