/*
 * UART_CFG.c
 *
 * Created: 3/1/2020 10:46:43 PM
 *  Author: A_ayman
 */ 

#include "UART_CFG.h"

// USART_CFG_t UART1_CFG = {USART_ASYNC_MODE,USART_RX_TX_Enable,USART_8BIT_DATA, USART_PARITY_DIS,USART_RISING_TRANSMIT,USART_1_STOP_BIT,USART_TX_Complete_Interrupt_Enable,USART_9600_BAUD_RATE};
// // UART1_CFG.CHAR_DATA_NUMBER = USART_8BIT_DATA;
// // UART1_CFG.STOP_BIT_SELECT = USART_1_STOP_BIT;
// // UART1_CFG.USART_BAUD_RATE_SELECT = USART_9600_BAUD_RATE;
// // UART1_CFG.USART_CLOCK_POLARITY = USART_RISING_TRANSMIT;
// // UART1_CFG.USART_MODE = USART_ASYNC_MODE;
// // UART1_CFG.USART_PARITY = USART_PARITY_DIS;
// // UART1_CFG.USART_RX_TX = USART_RX_TX_Enable;
// // UART1_CFG.USART_INTERRUPTS = USART_RX_Complete_Interrupt_Enable;
