/*
 * PortDriver_Lcfg.c
 *
 * Created: 4/8/2020 6:32:27 PM
 *  Author: Khaled
 */ 

#include "PortDriver_Lcfg.h" 
 

PortDriver_CfgType PortDriver_CfgArr[NUM_OF_ACTIVATED_CHANNELS] =
{/* Channel		                 PortDriver_Channel_Direction             PortDriver_Channel_Current_mA                      PortDriver_Channel_SlewRate                PortDriver_Channel_Attachment                    PortDriver_Channel_Function             PortDriver_Channel_Exti  */
	{PORTDRIVER_CHANNEL_E0,      PORTDRIVER_CHANNEL_DIRECTION_INPUT,      PORTDRIVER_CHANNEL_CURRENT_mA_2,                   PORTDRIVER_CHANNEL_SLEWRATE_DISABLE,       PORTDRIVER_CHANNEL_ATTACHMENT_NOTCONNECTED,      PORTDRIVER_CHANNEL_FUNCTION_X_DIO,      PORTDRIVER_CHANNEL_EXTI_DISABLE },
	{PORTDRIVER_CHANNEL_A0,      PORTDRIVER_CHANNEL_DIRECTION_OUTPUT,     PORTDRIVER_CHANNEL_CURRENT_mA_4,                   PORTDRIVER_CHANNEL_SLEWRATE_DISABLE,       PORTDRIVER_CHANNEL_ATTACHMENT_PULLUPRES   ,      PORTDRIVER_CHANNEL_FUNCTION_X_DIO,      PORTDRIVER_CHANNEL_EXTI_DISABLE },
	{PORTDRIVER_CHANNEL_A3,      PORTDRIVER_CHANNEL_DIRECTION_INPUT,      PORTDRIVER_CHANNEL_CURRENT_mA_8,                   PORTDRIVER_CHANNEL_SLEWRATE_DISABLE,       PORTDRIVER_CHANNEL_ATTACHMENT_PULLDOWNRES,       PORTDRIVER_CHANNEL_FUNCTION_X_DIO,      PORTDRIVER_CHANNEL_EXTI_DISABLE },
};
