/*
 * SysCtr_Cfg.c
 *
 * Created: 4/7/2020 9:09 AM
 *  Author: Ema
 */
#include"SysCtr_Cfg.h"

const uint8_t CfgArr[NUM_OF_PERIPHERALS][NUM_OF_CHANNELS]={
    /*****MUST be in the same order as in Data sheet*****/
    {RCGCTIMER_TIMER0,RCGCTIMER_TIMER1,RCGCTIMER_TIMER2,RCGCTIMER_TIMER3,RCGCTIMER_TIMER4,RCGCTIMER_TIMER5},
    {RCGCGPIO_PORTA,RCGCGPIO_PORTB,RCGCGPIO_PORTC,RCGCGPIO_PORTD,RCGCGPIO_PORTE,RCGCGPIO_PORTF}
};
