/*
 * ADC_Lcfg.c
 *
 *  Created on: Apr 26, 2020
 *      Author: K.Aladawy
 */



#include "ADC_Lcfg.h"


Adc_ConfigType ADC_Cfg =
{    
    ADC_SEQUENCER_3_MODULE0,
    ADC_TRIGGER_SOURCE_PPROCESSOR,
    ADC_NUM_OF_SAMPLE_IN_SEQUENCER_0,
    ADC_CHANNEL_AIN1,
    ADC_OPERATION_MODE_INTERRUPT,
    ADC_END_OF_SAMPLE_ACTIVE,
    ADC_SEQUENCER_PRIORITY_0,
    ADC_SAMPLE_PHASE_0_0,
    ADC_SAMPLE_MODE_SINGLE_END,
    ADC_SAMPLE_AVERAGING_CIRCUIT_No_HARDWARE_OVERSAMPLING
};
