/*
 * NVIC_lcfg.c
 *
 *      Author: Abdallah Heidar
 */

#ifndef SYSCTL_H_
#define SYSCTL_H_

#include "SysCtl_cfg.h"

#define SYSCTL_CLOCK_ENABLED			1
#define SYSCTL_CLOCK_DISABLED			0

#define SYSCTL_WATCHDOG_MODULE_REGMASK			(SYSCTL_WATCHDOG_MODULE_0_STATUS |		\
												(SYSCTL_WATCHDOG_MODULE_1_STATUS << 1))

#define SYSCTL_TIMER_MODULE_REGMASK				(SYSCTL_TIMER_MODULE_0_STATUS		|	\
												(SYSCTL_TIMER_MODULE_1_STATUS << 1)	|	\
												(SYSCTL_TIMER_MODULE_2_STATUS << 2)	|	\
												(SYSCTL_TIMER_MODULE_3_STATUS << 3)	|	\
												(SYSCTL_TIMER_MODULE_4_STATUS << 4)	|	\
												(SYSCTL_TIMER_MODULE_5_STATUS << 5))

#define SYSCTL_WTIMER_MODULE_REGMASK			(SYSCTL_WTIMER_MODULE_0_STATUS			|	\
												(SYSCTL_WTIMER_MODULE_1_STATUS << 1)	|	\
												(SYSCTL_WTIMER_MODULE_2_STATUS << 2)	|	\
												(SYSCTL_WTIMER_MODULE_3_STATUS << 3)	|	\
												(SYSCTL_WTIMER_MODULE_4_STATUS << 4)	|	\
												(SYSCTL_WTIMER_MODULE_5_STATUS << 5))

#define SYSCTL_GPIO_MODULE_REGMASK				(SYSCTL_GPIO_MODULE_0_STATUS		|	\
												(SYSCTL_GPIO_MODULE_1_STATUS << 1)	|	\
												(SYSCTL_GPIO_MODULE_2_STATUS << 2)	|	\
												(SYSCTL_GPIO_MODULE_3_STATUS << 3)	|	\
												(SYSCTL_GPIO_MODULE_4_STATUS << 4)	|	\
												(SYSCTL_GPIO_MODULE_5_STATUS << 5))

#define SYSCTL_UDMA_MODULE_REGMASK				SYSCTL_UDMA_MODULE_STATUS

#define SYSCTL_HIBERNATION_MODULE_REGMASK		SYSCTL_HIBERNATION_MODULE_STATUS

#define SYSCTL_UART_MODULE_REGMASK				(SYSCTL_UART_MODULE_0_STATUS		|	\
												(SYSCTL_UART_MODULE_1_STATUS << 1)	|	\
												(SYSCTL_UART_MODULE_2_STATUS << 2)	|	\
												(SYSCTL_UART_MODULE_3_STATUS << 3)	|	\
												(SYSCTL_UART_MODULE_4_STATUS << 4)	|	\
												(SYSCTL_UART_MODULE_5_STATUS << 5)	|	\
												(SYSCTL_UART_MODULE_6_STATUS << 6)	|	\
												(SYSCTL_UART_MODULE_7_STATUS << 7))

#define SYSCTL_SSI_MODULE_REGMASK				(SYSCTL_SSI_MODULE_0_STATUS			|	\
												(SYSCTL_SSI_MODULE_1_STATUS << 1)	|	\
												(SYSCTL_SSI_MODULE_2_STATUS << 2)	|	\
												(SYSCTL_SSI_MODULE_3_STATUS << 3))

#define SYSCTL_I2C_MODULE_REGMASK				(SYSCTL_I2C_MODULE_0_STATUS			|	\
												(SYSCTL_I2C_MODULE_1_STATUS << 1)	|	\
												(SYSCTL_I2C_MODULE_2_STATUS << 2)	|	\
												(SYSCTL_I2C_MODULE_3_STATUS << 3))

#define SYSCTL_USB_MODULE_REGMASK				SYSCTL_USB_MODULE_STATUS

#define SYSCTL_CAN_MODULE_REGMASK				(SYSCTL_CAN_MODULE_0_STATUS			|	\
												(SYSCTL_CAN_MODULE_1_STATUS << 1))

#define SYSCTL_ADC_MODULE_REGMASK				(SYSCTL_ADC_MODULE_0_STATUS			|	\
												(SYSCTL_ADC_MODULE_1_STATUS << 1))

#define SYSCTL_ACMP_MODULE_REGMASK				SYSCTL_ACMP_MODULE_STATUS

#define SYSCTL_PWM_MODULE_REGMASK				(SYSCTL_PWM_MODULE_0_STATUS			|	\
												(SYSCTL_PWM_MODULE_1_STATUS << 1))

#define SYSCTL_QEI_MODULE_REGMASK				(SYSCTL_QEI_MODULE_0_STATUS			|	\
												(SYSCTL_QEI_MODULE_1_STATUS << 1))

#define SYSCTL_EEPROM_MODULE_REGMASK			SYSCTL_EEPROM_MODULE_STATUS


extern void SysCtl_Init(void);


#endif /* SYSCTL_H_ */
