/*
 * NVIC_lcfg.c
 *
 *      Author: Abdallah Heidar
 */

#include "tm4c123gh6pm_registers.h"
#include "SysCtl.h"
#include "Privilege.h"

void SysCtl_Init(void)
{	

	System_SwitchToPrivileged();
	
	WRITE_BIT(SYSCTL_RCC_R, SYSCTL_RCC_BYPASS_B11) = 1;
	WRITE_BIT(SYSCTL_RCC_R, SYSCTL_RCC_USESYSDIV_B22) = 0;

	WRITE_BIT(SYSCTL_RCC_R, SYSCTL_RCC_MOSCDIS_B0) = 0;

	WRITE_BIT(SYSCTL_RCC_R, SYSCTL_RCC_XTAL_B6) = 1;
	WRITE_BIT(SYSCTL_RCC_R, SYSCTL_RCC_XTAL_B7) = 0;
	WRITE_BIT(SYSCTL_RCC_R, SYSCTL_RCC_XTAL_B8) = 1;
	WRITE_BIT(SYSCTL_RCC_R, SYSCTL_RCC_XTAL_B9) = 0;
	WRITE_BIT(SYSCTL_RCC_R, SYSCTL_RCC_XTAL_B10) = 1;

	WRITE_BIT(SYSCTL_RCC_R, SYSCTL_RCC_OSCSRC_B4) = 0;
	WRITE_BIT(SYSCTL_RCC_R, SYSCTL_RCC_OSCSRC_B5) = 0;

	WRITE_BIT(SYSCTL_RCC_R, SYSCTL_RCC_PWRDN_B13) = 0;

	WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_USERCC2_B31) = 1;
	
	WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_DIV400_B30) = 1;

	switch(SYSCTL_REQUIRED_FREQUENCY)
	{
	case SYSCTL_FREQ_8:
		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2_B23) = 0;
		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2_B24) = 0;
		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2_B25) = 0;
		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2_B26) = 1;
		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2_B27) = 1;
		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2_B28) = 0;

		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2LSB_B22) = 1;
		 break;
		 
	case SYSCTL_FREQ_12_5:
		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2_B23) = 1;
		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2_B24) = 1;
		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2_B25) = 1;
		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2_B26) = 1;
		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2_B27) = 0;
		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2_B28) = 0;

		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2LSB_B22) = 1;
		 break;
		 
	case SYSCTL_FREQ_16:
		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2_B23) = 0;
		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2_B24) = 0;
		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2_B25) = 1;
		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2_B26) = 1;
		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2_B27) = 0;
		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2_B28) = 0;

		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2LSB_B22) = 0;
		 break;
		 
	case SYSCTL_FREQ_25:
		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2_B23) = 1;
		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2_B24) = 1;
		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2_B25) = 1;
		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2_B26) = 0;
		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2_B27) = 0;
		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2_B28) = 0;

		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2LSB_B22) = 1;
		 break;
		 
	case SYSCTL_FREQ_33_33:
		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2_B23) = 1;
		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2_B24) = 0;
		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2_B25) = 1;
		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2_B26) = 0;
		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2_B27) = 0;
		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2_B28) = 0;

		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2LSB_B22) = 1;
		 break;
		 
	case SYSCTL_FREQ_40:
		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2_B23) = 0;
		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2_B24) = 0;
		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2_B25) = 1;
		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2_B26) = 0;
		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2_B27) = 0;
		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2_B28) = 0;

		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2LSB_B22) = 1;
		 break;
		 
	case SYSCTL_FREQ_50:
		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2_B23) = 1;
		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2_B24) = 1;
		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2_B25) = 0;
		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2_B26) = 0;
		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2_B27) = 0;
		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2_B28) = 0;

		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2LSB_B22) = 1;
		 break;
		 
	case SYSCTL_FREQ_66_67:
		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2_B23) = 0;
		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2_B24) = 1;
		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2_B25) = 0;
		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2_B26) = 0;
		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2_B27) = 0;
		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2_B28) = 0;

		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2LSB_B22) = 1;
		 break;
		 
	case SYSCTL_FREQ_80:
		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2_B23) = 0;
		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2_B24) = 1;
		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2_B25) = 0;
		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2_B26) = 0;
		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2_B27) = 0;
		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2_B28) = 0;

		 WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_SYSDIV2LSB_B22) = 0;
		 break;
		 
	default:
		 break;
	}
	
	while(READ_BIT(SYSCTL_RIS_R, SYSCTL_RIS_PLLLRIS_B6) == 0);
	
	WRITE_BIT(SYSCTL_RCC2_R, SYSCTL_RCC2_BYPASS2_B11) = 0;
	
	REGISTER(SYSCTL_RCGCWD_R) = SYSCTL_WATCHDOG_MODULE_REGMASK;
	REGISTER(SYSCTL_RCGCTIMER_R) = SYSCTL_TIMER_MODULE_REGMASK;
	REGISTER(SYSCTL_RCGCGPIO_R) = SYSCTL_GPIO_MODULE_REGMASK;
	REGISTER(SYSCTL_RCGCDMA_R) = SYSCTL_UDMA_MODULE_REGMASK;
	REGISTER(SYSCTL_RCGCHIB_R) = SYSCTL_HIBERNATION_MODULE_REGMASK;
	REGISTER(SYSCTL_RCGCUART_R) = SYSCTL_UART_MODULE_REGMASK;
	REGISTER(SYSCTL_RCGCSSI_R) = SYSCTL_SSI_MODULE_REGMASK;
	REGISTER(SYSCTL_RCGCI2C_R) = SYSCTL_I2C_MODULE_REGMASK;
	REGISTER(SYSCTL_RCGCUSB_R) = SYSCTL_USB_MODULE_REGMASK;
	REGISTER(SYSCTL_RCGCCAN_R) = SYSCTL_CAN_MODULE_REGMASK;
	REGISTER(SYSCTL_RCGCADC_R) = SYSCTL_ADC_MODULE_REGMASK;
	REGISTER(SYSCTL_RCGCACMP_R) = SYSCTL_ACMP_MODULE_REGMASK;
	REGISTER(SYSCTL_RCGCPWM_R) = SYSCTL_PWM_MODULE_REGMASK;
	REGISTER(SYSCTL_RCGCQEI_R) = SYSCTL_QEI_MODULE_REGMASK;
	REGISTER(SYSCTL_RCGCEEPROM_R) = SYSCTL_EEPROM_MODULE_REGMASK;
	REGISTER(SYSCTL_RCGCWTIMER_R) = SYSCTL_WTIMER_MODULE_REGMASK;

	System_SwitchToPrivileged();
}
